name: 'Release {version}'

tag_template: '{version}'

changelog_filename: CHANGELOG.md

template:
  categories:
    - title: 'ğŸ’¥ Breaking Changes'
      label: 'breaking'
    - title: 'âœ¨ Features'
      label: 'enhancement'
    - title: 'ğŸ› Bug Fixes'
      label: 'bug'
    - title: 'ğŸ§° Other Changes'
      label: ''

prerelease: false
